### ISSUE TITLE
Change attribute type example

### ISSUE THREAD

**Issue by seppo0010** [antirez/RESP3#4]
The current first example in attribute type is the following

```
|1<CR><LF>
    +key-popularity<CR><LF>
    %2
        :a
        ,0.1923
        :b
        ,0.0012
*2<CR><LF>
    :2039123
    :9543892
```

Ignoring the problems pointed out in #3, I think a better response and more clear documentation would be the following

```
*2<CR><LF>
    |1<CR><LF>
        %2<CR><LF>
        +key<CR><LF>
        $1<CR><LF>
        a<CR><LF>
        +popularity<CR><LF>
        ,0.1923<CR><LF>
    :2039123<CR><LF>
    |1<CR><LF>
        %2<CR><LF>
        +key<CR><LF>
        $1<CR><LF>
        b<CR><LF>
        +popularity<CR><LF>
        ,0.0012<CR><LF>
    :9543892<CR><LF>
```

This is actually more consistent with the other example where a single element has an attribute.

```
*3<CR><LF>
    :1<CR><LF>
    :2<CR><LF>
    |1<CR><LF>
        +ttl
        :3600
    :3<CR><LF>
```

I think the name and description is also confusing. I suggest calling it "metadata" and the description could change to something like this

> Metadata type contains metadata preceding the value to be returned in the form of a dictionary. It works like a map type with auxiliary information and it is followed by the actual value to be returned.

**Comment by antirez** [comment]
@seppo0010 the reason why I made the example where the attribute is "external" to the reply of the command, that is, at the same level, is because I expect it to be the way Redis will likely use such feature. What will happen is that a different part of the code, that is, when the keys are extracted from the command, may add the attributes, and later the command is processed as usually and the reply is generated. So the example is a lot closer to what people will see. It is not impossible that commands may generate attributes as well for certain elements, but this was put inside the protocol more in order to have a *general* support for such feature, and not because I currently have a clear use case. However also attributes may end nested in MULTI/EXEC and other cases where normal top-level replies get nested. Does this makes more sense?

**Comment by seppo0010** [comment]
It does. I was thinking what I would like to receive as a client, although both options are valid.
