### ISSUE TITLE
Guaranteeing reply vs pubsub might be too constraining

### ISSUE THREAD

**Issue by seppo0010** [antirez/RESP3#6]
> however the order of the commands and their replies is not affected: if a command is called, the next reply received will be the one relative of this command

I think this is how Redis will work due to its architecture, but I think it is unnecessarily constraining. I think the spec could avoid this guarantee and the clients should support the pubsub before the command reply.

I'm also not sure if the guarantee can actually be made, since the client may not know when the command was received and a push event may have been triggered by another connection writing concurrently.

**Comment by antirez** [comment]
@seppo0010 here there is a case where the specification does not actually document well what I meant, so you understood it in a different way compared to what I wanted to say. There is absolutely no guarantee of ordering, what I mean is that, if you *remove* the push types from the chat, because they are processed and accumulated differently, you'll see that a command is followed by the command reply (but again, if you ignore everything interleaved).

So for instance you could get:

```
C: GET foo
S: > pubsub channel foo
R: $3\r\nbar\r\n
```

or

```
C: GET foo
R: $3\r\nbar\r\n
S: > pubsub channel foo
```

And those are exactly valid replies to GET, because if you ignore the push messages, after the GET you'll see the reply to the GET. I guess this was not clear, right? I can try to improve the wording.

**Comment by seppo0010** [comment]
Oh, great then. I think the wording was confusing indeed. I was thinking the push was a reply but I think that's not the case. I think an example would be useful.

**Comment by antirez** [comment]
@seppo0010 yep, re-read it and not clear at all, fixing. Thanks!
